name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Package WordPress Application
      run: |
        tar -czvf wordpress_$(date +%F).tar.gz .
        mkdir -p builds && mv wordpress_$(date +%F).tar.gz builds/

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp builds/ s3://yousef-app/ --recursive
#
