name: Upload WordPress App to S3

on:
  push:
    branches:
      - master

jobs:
  s3-upload:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Package WordPress Application
      run: |
        tar -czvf app_$(date +%F).tar.gz . --exclude='.git' --exclude='node_modules'
        mkdir -p builds && mv app_$(date +%F).tar.gz builds/

    - name: Upload to S3
      run: |
        aws s3 cp builds/ s3://yourname_app/ --recursive
        aws s3api put-bucket-lifecycle-configuration --bucket yourname_app --region ${{ secrets.AWS_REGION }} --lifecycle-configuration file://lifecycle-config.json
