name: WordPress Deployment to S3 and Auto Scaling Group

on:
  push:
    branches:
      - master

jobs:
  s3-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Package WordPress Application
      run: |
        tar -czvf app_$(date +%F).tar.gz --exclude-vcs --exclude='.git' --exclude='node_modules' .
        mkdir -p builds && mv app_$(date +%F).tar.gz builds/

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp builds/ s3://yourname-app/ --recursive

    - name: Deploy to Auto Scaling Group
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws ssm send-command \
          --targets "Key=instanceIds,Values=<instance-id-1>,<instance-id-2>" \
          --document-name "AWS-RunShellScript" \
          --parameters commands="aws s3 cp s3://yourname-app/app_$(date +%F).tar.gz /tmp/app.tar.gz && tar -xzf /tmp/app.tar.gz -C /var/www/html && systemctl restart apache2" \
          --comment "Deploy WordPress application" 

